projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/API.ts
        docsFilePath: app/graphql
        region: us-east-1
        apiId: 4t6smronjnbfxanbk6si4mhlt4
        frontend: javascript
        framework: react
        maxDepth: 3
